#! /bin/sh

###############################################################################
#
# Text version of something like the GitHub's punchcard histogram.
#
###############################################################################


HEADER='Weekday,Hour,Commits'


histogram() {
    awk '
    BEGIN \
    {
        key_sep = "|";
    }

    {
        split($4, time, ":");
        weekday=$1;
        hour=time[1];

        commits[weekday key_sep hour]++
    }

    END \
    {
        for (period in commits) {
            split(period, p, key_sep);
            weekday = p[1];
            hour = p[2];
            printf "%s,%s,%d\n", weekday, hour, commits[period]
        }
    }
    '
}


main() {
    echo $HEADER;

    git log --format=%ad | histogram | sort -k 3 -t , -nr
}


main
